# Welcome to your Hyde configuration file.
# Here you can set global variables, configure extensions,
# and so much more. For complete documentation on configuring
# your Hyde project see https://hydecr.com/docs/configuring


# Site settings
# Use these settings to personalize your site. All configruations
# in this file are accessable in your `liquid` templates with the
# `site` prefix. For example `{{ site.title }}`.

title: Welcome to Hyde
description: >-
  Welcome to your new Hyde.cr website. You can modify this description
  in `_config.yml`.
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname and protocol of your site, e.g. https://example.com

social:
  twitter: hydecr
  facebook: hydecr
  github: hydecr
  # youtube: ""
  # dribbble: ""
  # behance: ""
  # mastodon: ""
  # telegram: ""
  # gitter: ""

# Theme
# This theme will be fetched from https://github.com/hydecr/hyde-theme-{theme}
# when running `hyde plugins update`. If you are using a custom theme
# make sure to comment this out or set it to the git url for the
# custom theme.
theme: "minima"
# theme: "https://github.com/hydecr/hyde-theme-minima"

# Plugins
# Hyde plugins are written in Crystal and can modify most aspects of the
# generation pipeline. Plugins can be listed by name (in which case
# they have to be registered at https://github.com/hydecr/plugins),
# or by git repo.
plugins:
  hyde-blog:
    config:
      permalink: /:date/:title
  i18n:
    config:
      path: /_langs/:locale
      root: en
  # hyde-blog:
  #   github: https://github.com/hydecr/hyde-blog

# Some ignores.
# The following files are automatically ignored by the build
# process, but were included for reference.
#
# exclude:
#   - .gitignore
#   - .editorconfig
#   - .travis.yml
#   - .sass-cache/
#   - .hyde-cache/
#   - lib/
#   - node_modules/
#   - vendor/

# Includes
# You can also include previously ignored files.
#
# include:
#   - README.md
